# Configuration file for the Jupyter UI.
#
# Each Jupyter UI option is configured by two keys: 'value' and 'readOnly'
# - The 'value' key contains the default value
# - The 'readOnly' key determines if the option will be available to users
#
# If the 'readOnly' key is present and set to 'true', the respective option
# will be disabled for users and only set by the admin. Also when a
# Notebook is POSTED to the API if a necessary field is not present then
# the value from the config will be used.
#
# If the 'readOnly' key is missing (defaults to 'false'), the respective option
# will be available for users to edit.
#
# Note that some values can be templated. Such values are the names of the
# Volumes as well as their StorageClass
spawnerFormDefaults:
  image:
    # The container Image for the user's Jupyter Notebook
    value: asia-northeast3-docker.pkg.dev/pyler-mlops/pyler-kubeflow-notebooks/jupyter-pytorch-full:v1.0
    # The list of available standard container Images
    options:
      - asia-northeast3-docker.pkg.dev/pyler-mlops/pyler-kubeflow-notebooks/jupyter-pytorch-full:v1.0
      - asia-northeast3-docker.pkg.dev/pyler-mlops/pyler-kubeflow-notebooks/jupyter-pytorch-cuda-full:v1.0
  imageGroupOne:
    # The container Image for the user's Group One Server
    # The annotation `notebooks.kubeflow.org/http-rewrite-uri: /`
    # is applied to notebook in this group, configuring
    # the Istio rewrite for containers that host their web UI at `/`
    value: asia-northeast3-docker.pkg.dev/pyler-mlops/pyler-kubeflow-notebooks/codeserver-python:v1.0
    # The list of available standard container Images
    options:
      - asia-northeast3-docker.pkg.dev/pyler-mlops/pyler-kubeflow-notebooks/codeserver-python:v1.0
  # If true, hide registry and/or tag name in the image selection dropdown
  hideRegistry: true
  hideTag: false
  allowCustomImage: true
  # If true, users can input custom images
  # If false, users can only select from the images in this config
  imagePullPolicy:
    # Supported values: Always, IfNotPresent, Never
    value: IfNotPresent
    readOnly: false
  cpu:
    # CPU for user's Notebook
    value: "2"
    # Factor by with to multiply request to calculate limit
    # if no limit is set, to disable set "none"
    limitFactor: "4"
    readOnly: false
  memory:
    # Memory for user's Notebook
    value: 4Gi
    # Factor by with to multiply request to calculate limit
    # if no limit is set, to disable set "none"
    limitFactor: "8"
    readOnly: false
  environment:
    value: {}
    readOnly: false
  workspaceVolume:
    # Workspace Volume to be attached to user's Notebook
    # If you don't want a workspace volume then delete the 'value' key
    value:
      mount: /home/pyler
      newPvc:
        metadata:
          name: "{notebook-name}-workspace"
        spec:
          resources:
            requests:
              storage: 10Gi
          accessModes:
            - ReadWriteOnce
    readOnly: false
  dataVolumes:
    # List of additional Data Volumes to be attached to the user's Notebook
    value: []
    # For example, a list with 2 Data Volumes:
    # value:
    #   - mount: /home/jovyan/datavol-1
    #     newPvc:
    #       metadata:
    #         name: '{notebook-name}-datavol-1'
    #       spec:
    #         resources:
    #           requests:
    #             storage: 5Gi
    #         accessModes:
    #           - ReadWriteOnce
    #   - mount: /home/jovyan/datavol-1
    #     existingSource:
    #       persistentVolumeClaim:
    #         claimName: test-pvc
    readOnly: false
  gpus:
    # Number of GPUs to be assigned to the Notebook Container
    value:
      # values: "none", "1", "2", "4", "8"
      num: "none"
      # Determines what the UI will show and send to the backend
      vendors:
        - limitsKey: "nvidia.com/gpu"
          uiName: "NVIDIA"
      # Values: "" or a `limits-key` from the vendors list
      vendor: ""
    readOnly: false
  affinityConfig:
    # If readonly, the default value will be the only option
    # value is a list of `configKey`s that we want to be selected by default
    value: false
    # The list of available affinity configs
    options: []
    #options:
    #  - configKey: "exclusive__n1-standard-2"
    #    displayName: "Exclusive: n1-standard-2"
    #    affinity:
    #      # (Require) Node having label: `node_pool=notebook-n1-standard-2`
    #      nodeAffinity:
    #        requiredDuringSchedulingIgnoredDuringExecution:
    #          nodeSelectorTerms:
    #            - matchExpressions:
    #                - key: "node_pool"
    #                  operator: "In"
    #                  values:
    #                   - "notebook-n1-standard-2"
    #      # (Require) Node WITHOUT existing Pod having label: `notebook-name`
    #      podAntiAffinity:
    #        requiredDuringSchedulingIgnoredDuringExecution:
    #          - labelSelector:
    #              matchExpressions:
    #                - key: "notebook-name"
    #                  operator: "Exists"
    #            namespaces: []
    #            topologyKey: "kubernetes.io/hostname"
    #readOnly: false
  tolerationGroup:
    # The default `groupKey` from the options list
    # If readonly, the default value will be the only option
    value: false
    # The list of available tolerationGroup configs
    options: []
    #options:
    #  - groupKey: "group_1"
    #    displayName: "Group 1: description"
    #    tolerations:
    #      - key: "key1"
    #        operator: "Equal"
    #        value: "value1"
    #        effect: "NoSchedule"
    #      - key: "key2"
    #        operator: "Equal"
    #        value: "value2"
    #        effect: "NoSchedule"
    readOnly: false
  shm:
    value: false
    readOnly: false
  configurations:
    # List of labels to be selected, these are the labels from PodDefaults
    # value:
    #   - add-gcp-secret
    #   - default-editor
    value: []
    readOnly: false
